### ISSUE TITLE
SWINTransformer + MMSEG "English" Notebook on custom dataset?

### ISSUE THREAD

**Issue by deshwalmahesh** [QWERDF007/Notebooks#1]
Hi, can you please provide an English notebook for Object Segmentation using `SWINTransformer` on custom dataset?

**Comment by QWERDF007** [comment]
> Hi, can you please provide an English notebook for Object Segmentation using `SWINTransformer` on custom dataset?

Sorry, my English is poor, I will provide a noteboo in Chinese. And I will try my best to provide the English version.

**Comment by deshwalmahesh** [comment]
> > Hi, can you please provide an English notebook for Object Segmentation using `SWINTransformer` on custom dataset?
> 
> Sorry, my English is poor, I will provide a noteboo in Chinese. And I will try my best to provide the English version.

Just the code would do. `variable names`

**Comment by QWERDF007** [comment]
> > > Hi, can you please provide an English notebook for Object Segmentation using `SWINTransformer` on custom dataset?
> > 
> > 
> > Sorry, my English is poor, I will provide a noteboo in Chinese. And I will try my best to provide the English version.
> 
> Just the code would do. `variable names`

Here’ s the English version: https://github.com/QWERDF007/Notebooks/blob/master/MachineLearning/OpenMMLab/mmseg%20train%20SwinTransformer%20on%20custon%20dataset.md

**Comment by deshwalmahesh** [comment]
> > > > Hi, can you please provide an English notebook for Object Segmentation using `SWINTransformer` on custom dataset?
> > > 
> > > 
> > > Sorry, my English is poor, I will provide a noteboo in Chinese. And I will try my best to provide the English version.
> > 
> > 
> > Just the code would do. `variable names`
> 
> Here’ s the English version: https://github.com/QWERDF007/Notebooks/blob/master/MachineLearning/OpenMMLab/mmseg%20train%20SwinTransformer%20on%20custon%20dataset.md

Thank you so much for the effort. Really appreciated.

**Comment by deshwalmahesh** [comment]
@QWERDF007  Just one more request hoping you're familiar and vell versed with segmentation. Can you please resolve these two queries?

1. [This stack question](https://datascience.stackexchange.com/questions/109175/is-it-possible-if-yes-then-how-to-provide-the-semantic-segmentation-results-o?noredirect=1#comment110935_109175)
2. [This Kaggle discussion](https://www.kaggle.com/discussions/questions-and-answers/313831)

**Comment by QWERDF007** [comment]
@deshwalmahesh I have two suggestions:
1. resize the output mask by using nearest neighbour interpolation, such as `cv2.resize(mask, (dsize, dsize), interpolation = cv2.INTER_NEAREST)`
2. using the model which output same resolution mask  as the input
